// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tablegamechain/checkers/game.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// All possible checkers game states
type GameState int32

const (
	// The game state is not set
	GameState_GAME_STATE_UNSPECIFIED GameState = 0
	// The game board is set up and ready to play
	GameState_GAME_STATE_READY GameState = 1
	// The game is in progress
	GameState_GAME_STATE_PLAYING GameState = 2
	// The game is complete - no more moves can be made
	GameState_GAME_STATE_COMPLETE GameState = 3
	// The game has expired - no further moves will be accepted
	GameState_GAME_STATE_EXPIRED GameState = 4
	// The game has been forfeited by one of the players
	GameState_GAME_STATE_FORFEITED GameState = 5
)

var GameState_name = map[int32]string{
	0: "GAME_STATE_UNSPECIFIED",
	1: "GAME_STATE_READY",
	2: "GAME_STATE_PLAYING",
	3: "GAME_STATE_COMPLETE",
	4: "GAME_STATE_EXPIRED",
	5: "GAME_STATE_FORFEITED",
}

var GameState_value = map[string]int32{
	"GAME_STATE_UNSPECIFIED": 0,
	"GAME_STATE_READY":       1,
	"GAME_STATE_PLAYING":     2,
	"GAME_STATE_COMPLETE":    3,
	"GAME_STATE_EXPIRED":     4,
	"GAME_STATE_FORFEITED":   5,
}

func (x GameState) String() string {
	return proto.EnumName(GameState_name, int32(x))
}

func (GameState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_727e9c33aa5cf801, []int{0}
}

// Game defines the Game type.
type Game struct {
	Board     string `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	Red       string `protobuf:"bytes,3,opt,name=red,proto3" json:"red,omitempty"`
	Black     string `protobuf:"bytes,4,opt,name=black,proto3" json:"black,omitempty"`
	Turn      string `protobuf:"bytes,5,opt,name=turn,proto3" json:"turn,omitempty"`
	State     string `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	StartTime int64  `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   int64  `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Creator   string `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_727e9c33aa5cf801, []int{0}
}
func (m *Game) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Game.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return m.Size()
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetBoard() string {
	if m != nil {
		return m.Board
	}
	return ""
}

func (m *Game) GetRed() string {
	if m != nil {
		return m.Red
	}
	return ""
}

func (m *Game) GetBlack() string {
	if m != nil {
		return m.Black
	}
	return ""
}

func (m *Game) GetTurn() string {
	if m != nil {
		return m.Turn
	}
	return ""
}

func (m *Game) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Game) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Game) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Game) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// A game identified by an index.
type IndexedGame struct {
	Index int64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Game  *Game `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
}

func (m *IndexedGame) Reset()         { *m = IndexedGame{} }
func (m *IndexedGame) String() string { return proto.CompactTextString(m) }
func (*IndexedGame) ProtoMessage()    {}
func (*IndexedGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_727e9c33aa5cf801, []int{1}
}
func (m *IndexedGame) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IndexedGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IndexedGame.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IndexedGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexedGame.Merge(m, src)
}
func (m *IndexedGame) XXX_Size() int {
	return m.Size()
}
func (m *IndexedGame) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexedGame.DiscardUnknown(m)
}

var xxx_messageInfo_IndexedGame proto.InternalMessageInfo

func (m *IndexedGame) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *IndexedGame) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

func init() {
	proto.RegisterEnum("tablegamechain.checkers.GameState", GameState_name, GameState_value)
	proto.RegisterType((*Game)(nil), "tablegamechain.checkers.Game")
	proto.RegisterType((*IndexedGame)(nil), "tablegamechain.checkers.IndexedGame")
}

func init() {
	proto.RegisterFile("tablegamechain/checkers/game.proto", fileDescriptor_727e9c33aa5cf801)
}

var fileDescriptor_727e9c33aa5cf801 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x6e, 0xd3, 0x40,
	0x14, 0x85, 0x3d, 0xb5, 0xd3, 0xd4, 0xb7, 0x9b, 0xd1, 0x10, 0xb5, 0x03, 0x52, 0xad, 0x92, 0x55,
	0x85, 0x54, 0x57, 0xc0, 0x92, 0x95, 0xa9, 0x27, 0x91, 0xa5, 0xfe, 0x58, 0x8e, 0x41, 0x94, 0x4d,
	0x34, 0xb1, 0x47, 0xc4, 0x4a, 0x6c, 0x47, 0xe3, 0x41, 0x0a, 0x6f, 0xc1, 0x23, 0xf0, 0x2c, 0xac,
	0x58, 0x66, 0xc9, 0x12, 0x25, 0x2f, 0x82, 0x66, 0x4c, 0x84, 0x41, 0xea, 0xee, 0x9e, 0x73, 0x3e,
	0x5f, 0xf9, 0x8c, 0x2e, 0x0c, 0x15, 0x9f, 0x2d, 0xc5, 0x27, 0x5e, 0x8a, 0x6c, 0xce, 0x8b, 0xea,
	0x2a, 0x9b, 0x8b, 0x6c, 0x21, 0x64, 0x73, 0xa5, 0x2d, 0x7f, 0x25, 0x6b, 0x55, 0x93, 0xd3, 0x7f,
	0x19, 0x7f, 0xcf, 0x0c, 0xbf, 0x23, 0x70, 0xc6, 0xbc, 0x14, 0x64, 0x00, 0xbd, 0x59, 0xcd, 0x65,
	0x4e, 0x0f, 0xce, 0xd1, 0x85, 0x9b, 0xb4, 0x82, 0x60, 0xb0, 0xa5, 0xc8, 0xa9, 0x6d, 0x3c, 0x3d,
	0x1a, 0x6e, 0xc9, 0xb3, 0x05, 0x75, 0xfe, 0x70, 0x5a, 0x10, 0x02, 0x8e, 0xfa, 0x2c, 0x2b, 0xda,
	0x33, 0xa6, 0x99, 0x35, 0xd9, 0x28, 0xae, 0x04, 0x3d, 0x6c, 0x49, 0x23, 0xc8, 0x19, 0x40, 0xa3,
	0xb8, 0x54, 0x53, 0x55, 0x94, 0x82, 0xf6, 0xcf, 0xd1, 0x85, 0x9d, 0xb8, 0xc6, 0x49, 0x8b, 0x52,
	0x90, 0xa7, 0x70, 0x24, 0xaa, 0xbc, 0x0d, 0x8f, 0x4c, 0xd8, 0x17, 0x55, 0x6e, 0x22, 0x0a, 0xfd,
	0x4c, 0x0a, 0xae, 0x6a, 0x49, 0x5d, 0xb3, 0x71, 0x2f, 0x87, 0xef, 0xe1, 0x38, 0xaa, 0x72, 0xb1,
	0x16, 0xf9, 0xbe, 0x4a, 0xa1, 0x25, 0x45, 0x66, 0x41, 0x2b, 0xc8, 0x4b, 0x70, 0x74, 0x7f, 0xd3,
	0xef, 0xf8, 0xd5, 0x99, 0xff, 0xc8, 0x8b, 0xf8, 0x7a, 0x45, 0x62, 0xd0, 0x17, 0xdf, 0x10, 0xb8,
	0x5a, 0x4e, 0xcc, 0x9f, 0x3f, 0x83, 0x93, 0x71, 0x70, 0xcb, 0xa6, 0x93, 0x34, 0x48, 0xd9, 0xf4,
	0xdd, 0xdd, 0x24, 0x66, 0xd7, 0xd1, 0x28, 0x62, 0x21, 0xb6, 0xc8, 0x00, 0x70, 0x27, 0x4b, 0x58,
	0x10, 0x3e, 0x60, 0x44, 0x4e, 0x80, 0x74, 0xdc, 0xf8, 0x26, 0x78, 0x88, 0xee, 0xc6, 0xf8, 0x80,
	0x9c, 0xc2, 0x93, 0x8e, 0x7f, 0x7d, 0x7f, 0x1b, 0xdf, 0xb0, 0x94, 0x61, 0xfb, 0xbf, 0x0f, 0xd8,
	0x87, 0x38, 0x4a, 0x58, 0x88, 0x1d, 0x42, 0x61, 0xd0, 0xf1, 0x47, 0xf7, 0xc9, 0x88, 0x45, 0x29,
	0x0b, 0x71, 0xef, 0xed, 0x9b, 0x1f, 0x5b, 0x0f, 0x6d, 0xb6, 0x1e, 0xfa, 0xb5, 0xf5, 0xd0, 0xd7,
	0x9d, 0x67, 0x6d, 0x76, 0x9e, 0xf5, 0x73, 0xe7, 0x59, 0x1f, 0x9f, 0x9b, 0x82, 0x97, 0xba, 0xc8,
	0x65, 0x7b, 0x18, 0xeb, 0xbf, 0xa7, 0xa1, 0xbe, 0xac, 0x44, 0x33, 0x3b, 0x34, 0xc7, 0xf1, 0xfa,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x79, 0x9c, 0x96, 0xd8, 0x42, 0x02, 0x00, 0x00,
}

func (m *Game) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Game) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Game) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintGame(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x4a
	}
	if m.EndTime != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.EndTime))
		i--
		dAtA[i] = 0x40
	}
	if m.StartTime != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.StartTime))
		i--
		dAtA[i] = 0x38
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintGame(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Turn) > 0 {
		i -= len(m.Turn)
		copy(dAtA[i:], m.Turn)
		i = encodeVarintGame(dAtA, i, uint64(len(m.Turn)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Black) > 0 {
		i -= len(m.Black)
		copy(dAtA[i:], m.Black)
		i = encodeVarintGame(dAtA, i, uint64(len(m.Black)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Red) > 0 {
		i -= len(m.Red)
		copy(dAtA[i:], m.Red)
		i = encodeVarintGame(dAtA, i, uint64(len(m.Red)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Board) > 0 {
		i -= len(m.Board)
		copy(dAtA[i:], m.Board)
		i = encodeVarintGame(dAtA, i, uint64(len(m.Board)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *IndexedGame) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IndexedGame) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IndexedGame) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Game != nil {
		{
			size, err := m.Game.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGame(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Index != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGame(dAtA []byte, offset int, v uint64) int {
	offset -= sovGame(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Game) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Board)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	l = len(m.Red)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	l = len(m.Black)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	l = len(m.Turn)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	if m.StartTime != 0 {
		n += 1 + sovGame(uint64(m.StartTime))
	}
	if m.EndTime != 0 {
		n += 1 + sovGame(uint64(m.EndTime))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	return n
}

func (m *IndexedGame) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovGame(uint64(m.Index))
	}
	if m.Game != nil {
		l = m.Game.Size()
		n += 1 + l + sovGame(uint64(l))
	}
	return n
}

func sovGame(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGame(x uint64) (n int) {
	return sovGame(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Game) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Game: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Game: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Board", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Board = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Red", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Red = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Black", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Black = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Turn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Turn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			m.StartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			m.EndTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IndexedGame) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IndexedGame: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IndexedGame: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Game", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Game == nil {
				m.Game = &Game{}
			}
			if err := m.Game.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGame(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGame
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGame
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGame
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGame
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGame
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGame
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGame        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGame          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGame = fmt.Errorf("proto: unexpected end of group")
)
